const GC_CLUBS = [
    {sport: 'Team SF', teamName: 'Team SF', webSite: 'www.teamsf.ning.com', contact: 'Reggie Snowden', email: 'tycole.sf@gmail.com', notes: ''},
    {sport: 'BADMINTON', teamName: '(help us start one)', webSite: 'www.uswebcity.com/badminton.html', contact: 'n/a', email: 'n/a', notes: ''},
    {sport: 'BASKETBALL', teamName: 'SF Gay Basketball', webSite: '<a href="http://www.sfgba.com/home" target="new">SF Gay BasketBall</a>', contact: 'see website', email: 'info@sfgba.com', notes: ''},
    {sport: 'BODYBUILDING', teamName: '(help us start one)', webSite: 'n/a', contact: 'n/a', email: 'n/a', notes: ''},
    {sport: 'BOWLING', teamName: 'n/a', webSite: 'www.facebook/sfgay.bowling', contact: 'Doug', email: 'dougsf@gmail.com', notes: ''},
    {sport: 'BOXING', teamName: 'n/a', webSite: 'n/a', contact: 'n/a', email: 'n/a', notes: ''},
    {sport: 'CHEER LEADING', teamName: 'CHEER SF', webSite: 'www.cheersf.org', contact: 'n/a', email: 'contact@cheersf.org', notes: ''},
    {sport: 'CYCLING', teamName: 'DIFFERENT SPOKES', webSite: 'www.dssf.org', contact: 'Larry', email: 'membership@dssf.org', notes: ''},
    {sport: 'DANCESPORT', teamName: 'DANCESPORT', webSite: '<a href="https://www.facebook.com/groups/Gaygamesdancesport/" target="new">Dance sport</a>', contact: 'Robert', email: 'rjcortlandt@gmail.com', notes: ''},
    {sport: 'FLAG FOOTBALL (M)', teamName: 'SF GAY FLAG FOOTBALL LEAGUE', webSite: 'http://www.sfgffl.org/', contact: 'n/a', email: 'info@sfgffl.org', notes: ''},
    {sport: 'FLAG FOOTBALL (W)', teamName: 'SF WOMEN`S FLAG FOOTBALL LEAGUE', webSite: 'www.sfwffl.org', contact: 'n/a', email: 'info@sfwffl.org', notes: ''},
    {sport: 'ICE HOCKEY', teamName: 'SF QUAKES', webSite: 'www.sfquakes.com', contact: 'n/a', email: '" quakes@sfquakes.com"', notes: ''},
    {sport: 'MARTIAL ARTS', teamName: 'INTERNATIONAL ASSOCIATION OF GAY & LESBIAN MARTIAL ARTISTS', webSite: 'WWW.IAGLMA.ORG', contact: 'Ken Craig', email: 'KenCraigCA@gmail.com', notes: ''},
    {sport: 'MOTORCYCLING', teamName: 'HOMOTO MOTORCYCLING CLUB', webSite: 'https://www.meetup.com/Homoto-Motorcycle-Club/', contact: 'n/a', email: 'n/a', notes: ''},
    {sport: 'POOL/BILLARDS', teamName: 'SF POOL ASSOCIATION', webSite: 'www.sfpapool.org', contact: 'see website', email: 'n/a', notes: ''},
    {sport: 'RACQUETBALL', teamName: 'BAY AREA RACQUETBALL', webSite: '', contact: 'Doug Litwin', email: '"dougsf@gmail.com', notes: ''},
    {sport: 'RODEO', teamName: 'BAY AREA RODEO', webSite: '"www.bayarearodeo.com "', contact: 'outreach coordinator', email: 'outreach@bayarearodeo.com', notes: ''},
    {sport: 'ROWING', teamName: 'SF BAY BLADES', webSite: 'http://www.meetup.com/San-Francisco-Bay-Blades', contact: 'recruiter', email: 'alchase123@gmail.com', notes: ''},
    {sport: 'RUGBY (M)', teamName: 'SF FOG', webSite: 'www.sffog.org', contact: 'see website', email: 'n/a', notes: ''},
    {sport: 'RUGBY (W)', teamName: '', webSite: '', contact: 'n/a', email: 'n/a', notes: ''},
    {sport: 'RUNNING', teamName: 'SF FRONTRUNNERS', webSite: 'www.sffr.org', contact: 'Brian-men`s contact Delip-women`s contact', email: 'mens-contact@sffr.org womens-contact@sffr.org', notes: ''},
    {sport: 'RUNNING', teamName: 'BAYLANDS FRONTRUNNERS', webSite: 'www.baylands.org', contact: 'see website', email: 'n/a', notes: ''},
    {sport: 'RUNNNG', teamName: 'EASTBAY FRONTRUNNERS', webSite: 'www.eastbayfrontrunners.org', contact: 'Donald Fritsche', email: 'ebfrw@yahoo.com', notes: ''},
    {sport: 'SAILING', teamName: 'SF SAILING CLUB', webSite: 'http://groups.yahoo.com/group/SFSailingTeam/', contact: 'n/a', email: 'n/a', notes: ''},
    {sport: 'SKI & SNOWBOARD', teamName: 'SAGA NORTH', webSite: 'www.saganorth.com', contact: 'Thib Guicherd-Callin', email: 'saga-president@saganorth.com', notes: ''},
    {sport: 'SKI & SNOWBOARD', teamName: 'SKI BUMS', webSite: 'http://www.ski-bums.org/cali', contact: 'n/a', email: 'contactus@ski-bums.org', notes: ''},
    {sport: 'SOCCER', teamName: 'SF SPIKES', webSite: 'www.sfspikes.com', contact: 'Mathew', email: 'info@sfspikes.com', notes: ''},
    {sport: 'SOFTBALL', teamName: 'SF GAY SOFTBALL LEAGUE', webSite: 'www.sfgsl.org', contact: 'see website', email: 'see website', notes: ''},
    {sport: 'SPORTDANCING /BALLROOM', teamName: 'TRIP THE LIGHT FANTASTIC', webSite: 'www.tripthelightfantastic.org/', contact: 'Zoe', email: 'zoe@tripthelightfantastic.org', notes: ''},
    {sport: 'SQUASH', teamName: '', webSite: '', contact: 'n/a', email: 'n/a', notes: ''},
    {sport: 'SWIM-DIVING', teamName: 'TSUNAMI -DIVING', webSite: 'www.sftsunami.org/', contact: 'info', email: 'info@sftsunami.org', notes: ''},
    {sport: 'SWIM-SYNCHRO', teamName: 'TSUNAMI SYNCHRO', webSite: 'www.sftsunami.org/', contact: 'info', email: 'info@sftsunami.org', notes: ''},
    {sport: 'SWIM-WATER POLO', teamName: 'TSUNAMI WATER POLO', webSite: 'www.sftsunami.org/', contact: 'info', email: 'info@sftsunami.org', notes: ''},
    {sport: 'SWIMMING', teamName: 'TSUNAMI SWIM CLUB', webSite: 'www.sftsunami.org/', contact: 'info', email: 'info@sftsunami.org', notes: ''},
    {sport: 'TABLE TENNIS', teamName: '', webSite: '', contact: 'n/a', email: 'n/a', notes: ''},
    {sport: 'TENNIS', teamName: 'GLTF', webSite: 'www.gltf.org', contact: 'Membership director', email: '" membership@gltf.org"', notes: ''},
    {sport: 'TRACK & FIELD', teamName: 'SF TRACK & FIELD CLUB', webSite: 'www.sftrackandfield.com', contact: 'Membership director', email: 'email first to website.', notes: ''},
    {sport: 'TRIATHLON', teamName: '(help us start one)', webSite: 'n/a', contact: 'n/a', email: 'n/a', notes: ''},
    {sport: 'VOLLEYBALL', teamName: 'Balls of Furry Volleyball.', webSite: 'www.ballsoffurryvolleyball.org/', contact: 'Richard Sucre-commissioner', email: 'sfballsoffurry@gmail.com', notes: ''},
    {sport: 'WRESTLING', teamName: 'GOLDEN GATE WRESTLING CLUB', webSite: 'www.ggwc.org', contact: 'Gene Dermody', email: 'wrestler@dermodynamics.com', notes: ''}
];

const GC_EVENTS = [
    {id: 2022110101, title: "Gay Games, Hong Kong 11 - November 2022", description: "Gay Games, Hong Kong 11 - November 2022",
        location2: "Hong Kong", location1: "Hong Kong", website: "https://gghk2022.com/", image: "images/gghk11.png",
        contact: "https://gghk2022.com/", startDate: "2022-11-01", dates: "2022-11-01 - 2022-11-30", time: "AM", status: 1}
];
